web:
  build: .
  command: 'bash -c ''target/universal/stage/bin/notesandthings'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  links:
    - db

db:
  image: mongo
  volumes:
    - db:/data/db
  ports:
    - '27017:27017'
  expose:
    - '27017'

shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
  links:
    - db

